spring:
  # PostgreSQL Database Configuration for Development
  datasource:
    url: jdbc:postgresql://localhost:5432/restbook
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

# Cache Configuration
cache:
  redis:
    time-to-live: 600000 # 10 minutes in milliseconds

# Server Configuration
server:
  port: 8080

  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: UTC

# Logging Configuration
logging:
  level:
    com.example.restbook: DEBUG
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
